# Generated by Django 2.2.12 on 2020-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('female_number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('situation', models.CharField(max_length=50)),
                ('time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemaID', models.IntegerField()),
                ('table_name', models.CharField(max_length=20)),
                ('describe', models.TextField()),
            ],
        ),
    ]
